language: node_js
node_js:
  - '4'
services:
  - docker
script: 
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
# Do similar for other three images

# Tagging
  - docker tag udagram-api-feed afifii/udagram-api-feed:v1
  - docker tag udagram-api-user afifii/udagram-api-user:v1
  - docker tag reverseproxy afifii/reverseproxy:v1
  - docker tag udagram-frontend afifii/udagram-frontend:v1
# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push afifii/udagram-api-feed:v1
  - docker push afifii/udagram-api-user:v1
  - docker push afifii/reverseproxy:v1
  - docker push afifii/udagram-frontend:v1
# Do similar for other three images